### ISSUE TITLE
Expectation of delayed value with start-with value fails

### ISSUE THREAD

**Issue by rjkip** [cyclejs/time#12]
I've written the following Time driver learning test (using Jest), because I couldn't figure out why my own test was failing. The below test fails unexpectedly. Is this a bug, or should this behaviour be explained in the documentation perhaps?

```js
import { mockTimeSource } from "@cycle/time";
import xs from "xstream";

describe("@cycle/time learning test", () => {
    // [...]

    it("supports delayed value with start-with value", () => {
        const Time = mockTimeSource();

        const actual$ = xs.of("B").compose(Time.delay(40)).startWith("A");
        const expected$ = Time.diagram(`A-B|`);

        Time.assertEqual(actual$, expected$);

        return new Promise((resolve, reject) => {
            Time.run(err => err ? reject(err) : resolve());
        });
    });
});
```

Unexpected failure:

```
 FAIL  src/cycle/__tests__/time.test.js
  ● @cycle/time learning test › supports delayed value with start-with value

    
          Expected
    
          A-B|
    
          Got
    
          A-|
    
          Failed because
    
          Length of actual and expected differs
      
      
            
          
      at checkEqual (node_modules/@cycle/time/dist/assert-equal.js:53:24)
      at Object.xstream_1.default.combine.addListener.complete (node_modules/@cycle/time/dist/assert-equal.js:79:17)
      at Stream._c (node_modules/xstream/index.js:917:18)
      at CombineListener._c (node_modules/xstream/index.js:162:19)
      at MemoryStream.Stream._c (node_modules/xstream/index.js:917:18)
      at Object.complete (node_modules/@cycle/time/dist/record.js:14:25)
      at Stream._c (node_modules/xstream/index.js:917:18)
      at Stream.shamefullySendComplete (node_modules/xstream/index.js:1664:14)
      at Immediate.processEvent (node_modules/@cycle/time/dist/run-virtually.js:33:35)
      at runCallback (timers.js:570:20)
      at tryOnImmediate (timers.js:550:5)
      at processImmediate [as _immediateCallback] (timers.js:529:5)
```

Installed packages:

```sh-session
$ grep -A1 -E '^"?(@cycle|jest|xstream)' yarn.lock | grep -vE '^--$'
"@cycle/base@4.2":
  version "4.2.0"
"@cycle/base@^4.3.0":
  version "4.3.0"
"@cycle/time@^0.4.0":
  version "0.4.0"
"@cycle/xstream-adapter@3.x.x":
  version "3.1.0"
"@cycle/xstream-run@^4.2.0":
  version "4.2.0"
jest-changed-files@^17.0.2:
  version "17.0.2"
jest-cli@^18.1.0:
  version "18.1.0"
jest-config@^18.1.0:
  version "18.1.0"
jest-diff@^18.1.0:
  version "18.1.0"
jest-environment-jsdom@^18.1.0:
  version "18.1.0"
jest-environment-node@^18.1.0:
  version "18.1.0"
jest-file-exists@^17.0.0:
  version "17.0.0"
jest-haste-map@^18.1.0:
  version "18.1.0"
jest-jasmine2@^18.1.0:
  version "18.1.0"
jest-matcher-utils@^18.1.0:
  version "18.1.0"
jest-matchers@^18.1.0:
  version "18.1.0"
jest-mock@^18.0.0:
  version "18.0.0"
jest-resolve-dependencies@^18.1.0:
  version "18.1.0"
jest-resolve@^18.1.0:
  version "18.1.0"
jest-runtime@^18.1.0:
  version "18.1.0"
jest-snapshot@^18.1.0:
  version "18.1.0"
jest-util@^18.1.0:
  version "18.1.0"
jest-validate@18.2.0:
  version "18.2.0"
jest@^18.1.0:
  version "18.1.0"
xstream@*, xstream@^10.2.0:
  version "10.2.0"
```

**Comment by Widdershin** [comment]
This test should pass with `v0.5.0`, please update and let me know if that solves the problem.

This was due to an issue where if a stream completed at the same time as emitting the final event, the completion would happen first. As of `v0.5.0` there is a guarantee that the completion will happen last in that case.

**Comment by rjkip** [comment]
Confirmed! Thanks for the work you put into this library, it's proving to be quite valuable! :)

**Comment by Widdershin** [comment]
You're welcome. Thanks for reporting this issue. Let me know if you have any other feedback, issues or ideas for improvement.

If you end up open sourcing any of the work you do with `@cycle/time`, I would love to see it.
